# Generated by Django 5.0.14 on 2025-07-07 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.EmailField(max_length=30)),
                ('Email', models.CharField(max_length=50)),
                ('Password', models.CharField(default='123456', max_length=50)),
                ('Phone', models.IntegerField(null=True)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'female')], max_length=10, null=True)),
                ('isadmin', models.BooleanField(default=False)),
                ('age', models.IntegerField(default=0)),
                ('silvercoins', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('description', models.TextField(default='No description available ')),
                ('Author', models.CharField(max_length=30)),
                ('Price', models.IntegerField()),
                ('image', models.ImageField(default='s.png', upload_to='static/images')),
                ('available', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Pages.category')),
            ],
        ),
        migrations.CreateModel(
            name='Interactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pages.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pages.user')),
            ],
            options={
                'verbose_name': 'Interaction',
            },
        ),
        migrations.CreateModel(
            name='BorrowedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pages.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pages.user')),
            ],
        ),
    ]
