# Generated by Django 5.2.1 on 2025-05-15 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'female')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='borrowedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pages.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pages.user')),
            ],
        ),
    ]
