# Generated by Django 5.0.14 on 2025-07-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Name',
            new_name='Fname',
        ),
        migrations.AddField(
            model_name='user',
            name='Lname',
            field=models.EmailField(default=' ', max_length=30),
        ),
    ]
